# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 24.9.2
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-openblas.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2024.9.24-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2022.0.1-h06a4308_3633.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.40-h12ee557_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pybind11-abi-4-hd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2024b-h04d1e81_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libgomp-14.2.0-h77fa898_1.conda
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-14.2.0-h77fa898_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-14.2.0-h69a702a_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran5-14.2.0-hd5240d6_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-14.2.0-hc0a3c3a_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libuv-1.49.2-hb9d3cd8_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libzlib-1.3.1-hb9d3cd8_2.conda
https://conda.anaconda.org/conda-forge/linux-64/openssl-3.4.0-hb9d3cd8_0.conda
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h4bc722e_7.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-14.2.0-h69a702a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnsl-2.0.0-h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libsqlite-3.47.0-hadc24fc_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-14.2.0-h4852527_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.38.1-h0b41bf4_0.conda
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.5-he02047a_1.conda
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.13-noxft_h4845f30_101.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.6-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.3.1-hb9d3cd8_2.conda
https://conda.anaconda.org/conda-forge/linux-64/icu-75.1-he02047a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-14.2.0-h69a702a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2022.1.0-hc2b9512_224.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.9.0-1_h86c2bf4_netlib.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.28-pthreads_h94d23a6_0.conda
https://conda.anaconda.org/conda-forge/linux-64/nodejs-20.17.0-hc55a1b2_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python-3.9.18-h0755675_0_cpython.conda
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.47.0-h9eae976_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/aiohappyeyeballs-2.4.0-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/aiolimiter-1.1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/annotated-types-0.6.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/async-timeout-4.0.3-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-24.2.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blinker-1.6.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-python-1.0.9-py39h6a678d5_8.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2024.8.30-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-3.3.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.1.7-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/exceptiongroup-1.2.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/flit-core-3.6.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/frozenlist-1.4.0-py39h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/h11-0.14.0-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/hpack-4.0.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/hyperframe-6.0.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.7-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/itsdangerous-2.2.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/joblib-1.4.2-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.9.0-7_ha36c22a_netlib.conda
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.9.0-7_ha36c22a_netlib.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.3-py39h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/mdurl-0.1.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/multidict-6.0.4-py39h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.26.4-py39h8a23956_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-24.1-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/pygments-2.18.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-dotenv-1.0.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-multipart-0.0.17-pyhff2d567_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.9-2_cp39.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-75.1.0-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/shellingham-1.5.4-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sniffio-1.3.0-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/tabulate-0.9.0-pyhd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tenacity-8.2.3-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/threadpoolctl-3.5.0-py39h2f386ee_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.11.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/yarn-4.5.1-h31011fe_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.20.2-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/aiosignal-1.2.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/dnspython-2.7.0-pyhff2d567_0.conda
https://conda.anaconda.org/conda-forge/linux-64/greenlet-3.1.1-py39hf88036b_0.conda
https://conda.anaconda.org/conda-forge/noarch/h2-4.1.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/httptools-0.6.1-py39h8cd3c5a_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-7.0.1-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.4-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libfaiss-1.8.0-h0ce047f_1_cpu.conda
https://conda.anaconda.org/conda-forge/linux-64/libfaiss-avx2-1.7.0-h1234567_8_cpu.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/markdown-it-py-3.0.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/mkl-service-2.4.0-py39hb699420_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.26.4-py39heeff2f4_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-24.2-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/plotly-5.24.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-6.0.2-py39h8cd3c5a_1.conda
https://conda.anaconda.org/conda-forge/noarch/typer-slim-0.13.0-pyhff2d567_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing-extensions-4.11.0-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-2.2.3-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/uvloop-0.21.0-py39h8cd3c5a_1.conda
https://conda.anaconda.org/conda-forge/linux-64/watchfiles-0.24.0-py39he612d8f_1.conda
https://conda.anaconda.org/conda-forge/linux-64/websockets-13.1-py39h8cd3c5a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-3.0.3-py39h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yarl-1.11.0-py39h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/aiohttp-3.10.5-py39h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/email-validator-2.2.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/faiss-1.8.0-py39h1df3c28_1_cpu.conda
https://conda.anaconda.org/conda-forge/noarch/flask-3.0.3-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/httpcore-1.0.6-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/mkl_fft-1.3.1-py39h051f8f4_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mkl_random-1.2.2-py39h8b66066_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.32.3-py39h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/rich-13.9.4-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.13.1-py39heeff2f4_0.conda
https://conda.anaconda.org/conda-forge/linux-64/sqlalchemy-2.0.36-py39h8cd3c5a_0.conda
https://conda.anaconda.org/conda-forge/noarch/uvicorn-standard-0.32.0-h31011fe_1.conda
https://conda.anaconda.org/conda-forge/linux-64/watchdog-6.0.0-py39hf3d152e_0.conda
https://conda.anaconda.org/conda-forge/noarch/email_validator-2.2.0-hd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/faiss-cpu-1.8.0-h718b53a_1.conda
https://conda.anaconda.org/conda-forge/noarch/httpx-0.27.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/linux-64/scikit-learn-1.5.2-py39h4b7350c_1.conda
https://conda.anaconda.org/conda-forge/noarch/typer-slim-standard-0.13.0-hd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/voyageai-0.2.4-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/typer-0.13.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/fastapi-cli-0.0.5-pyhd8ed1ab_1.conda
